# makefile for scheduler

scheduler: scheduler.cpp generator info.h generator
	g++ --std=c++11 scheduler.cpp -o scheduler
	
generator: generator.cpp info.h
	g++ --std=c++11 generator.cpp -o generator
